-- MySQL Script generated by MySQL Workbench
-- 11/22/18 16:58:06
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Recibo
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Recibo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Recibo` DEFAULT CHARACTER SET utf8 ;
USE `Recibo` ;

-- -----------------------------------------------------
-- Table `Recibo`.`uf`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Recibo`.`uf` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Recibo`.`cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Recibo`.`cidade` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `uf_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`, `uf_id`),
  INDEX `fk_cidade_uf1_idx` (`uf_id` ASC),
  CONSTRAINT `fk_cidade_uf1`
    FOREIGN KEY (`uf_id`)
    REFERENCES `Recibo`.`uf` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
